import { existsSync, mkdirSync, copyFileSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SKILLS_SOURCE = join(__dirname, '../../skills');

// Installa una skill per un tool specifico
export function installSkill(skillId, tool, targetRoot) {
  const skillSource = join(SKILLS_SOURCE, skillId, 'SKILL.md');

  if (!existsSync(skillSource)) {
    return { ok: false, reason: `Skill source not found: ${skillId}` };
  }

  if (tool.skillsPath) {
    // Tool con cartella skills dedicata (Copilot, Claude, Cursor, Windsurf)
    const destDir = join(targetRoot, tool.skillsPath, skillId);
    mkdirSync(destDir, { recursive: true });
    copyFileSync(skillSource, join(destDir, 'SKILL.md'));
    return { ok: true, path: join(tool.skillsPath, skillId, 'SKILL.md') };

  } else if (tool.agentsFile) {
    // Tool che usano un file unico (Codex, Gemini, Antigravity)
    appendToAgentsFile(skillId, skillSource, tool.agentsFile, targetRoot);
    return { ok: true, path: tool.agentsFile };
  }

  return { ok: false, reason: 'Tool has no skillsPath or agentsFile defined' };
}

// Rimuove una skill installata
export function removeSkill(skillId, tool, targetRoot) {
  if (tool.skillsPath) {
    const destDir = join(targetRoot, tool.skillsPath, skillId);
    if (existsSync(destDir)) {
      import('fs').then(fs => fs.rmSync(destDir, { recursive: true }));
      return { ok: true };
    }
    return { ok: false, reason: 'Skill not installed' };
  }
  // Per AGENTS.md non rimuoviamo — troppo rischioso parsare e modificare
  return { ok: false, reason: `Manual removal required from ${tool.agentsFile}` };
}

// Legge la config locale OpenBA
export function readConfig(targetRoot) {
  const configPath = join(targetRoot, '.openba', 'config.json');
  if (!existsSync(configPath)) return null;
  try {
    return JSON.parse(readFileSync(configPath, 'utf8'));
  } catch {
    return null;
  }
}

// Scrive la config locale OpenBA
export function writeConfig(targetRoot, config) {
  const configDir = join(targetRoot, '.openba');
  mkdirSync(configDir, { recursive: true });
  const configPath = join(configDir, 'config.json');
  writeFileSync(configPath, JSON.stringify({ ...config, updatedAt: new Date().toISOString() }, null, 2));
}

// Aggiunge una skill al file AGENTS.md / GEMINI.md
function appendToAgentsFile(skillId, skillSource, agentsFile, targetRoot) {
  const destPath = join(targetRoot, agentsFile);
  const skillContent = readFileSync(skillSource, 'utf8');

  const separator = `\n\n<!-- OpenBA skill: ${skillId} -->\n`;
  const block = separator + skillContent;

  if (existsSync(destPath)) {
    const existing = readFileSync(destPath, 'utf8');
    // Non aggiungere se già presente
    if (existing.includes(`<!-- OpenBA skill: ${skillId} -->`)) return;
    writeFileSync(destPath, existing + block);
  } else {
    const header = `# OpenBA Skills\n\nThis file contains OpenBA skill instructions for your AI assistant.\nDo not edit this file manually — use \`openba update\` to refresh.\n`;
    writeFileSync(destPath, header + block);
  }
}

// Versione corrente del package
export function getPackageVersion() {
  const pkgPath = join(__dirname, '../../package.json');
  return JSON.parse(readFileSync(pkgPath, 'utf8')).version;
}
